server:
  port: 9090

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-address: ${KAFKA_BROKER:"localhost:9200"}
    bootstrap-servers: ${KAFKA_BROKER:"localhost:9200"}
    number-partitions: ${KAFKA_NUMBER_PARTITIONS:3}
    replication-factor: ${KAFKA_REPLICATION_FACTOR:3}
